<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class FinalWoodTypesSeeder extends Seeder
{
    private function createProducts($products)
    {
        foreach ($products as $productData) {
            $productData['status'] = 'active';
            $product = Product::create($productData);
            
            ProductImage::create([
                'product_id' => $product->id,
                'image_url' => '/storage/images/products/' . $product->slug . '-1.jpg',
                'alt_text' => $product->name . ' - Image principale',
                'sort_order' => 1,
                'is_primary' => true
            ]);
        }
    }

    public function run(): void
    {
        $chauffageCategory = Category::where('slug', 'bois-de-chauffage')->first();
        $cuissonCategory = Category::where('slug', 'bois-de-cuisson')->first();

        // ÉPICÉA - 10 produits (résineux parfumé)
        $epiceaProducts = [
            [
                'name' => 'Épicéa 25cm - Sacs 40kg',
                'slug' => 'epicea-25cm-sacs-40kg',
                'description' => "Épicéa sec en sacs de 40kg, format 25cm. Résineux de qualité pour allumage et chauffage d'appoint. Combustion vive avec bonne montée en température.",
                'short_description' => 'Épicéa 25cm, combustion vive et parfumée',
                'wood_type' => 'epicea',
                'usage_type' => 'chauffage',
                'humidity_rate' => 21.5,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 5.50,
                'stock_quantity' => 90,
                'min_order_quantity' => 4,
                'alert_stock_level' => 18,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Épicéa 30cm - Palette Standard',
                'slug' => 'epicea-30cm-palette-standard',
                'description' => "Épicéa en palette format 30cm. Résineux économique pour chauffage d'appoint. Parfum agréable de résine. Allumage facile et combustion vive.",
                'short_description' => 'Épicéa 30cm palette, parfum résine',
                'wood_type' => 'epicea',
                'usage_type' => 'chauffage',
                'humidity_rate' => 22.0,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 72.00,
                'stock_quantity' => 35,
                'min_order_quantity' => 1,
                'alert_stock_level' => 7,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Épicéa 20cm - Sacs 25kg',
                'slug' => 'epicea-20cm-sacs-25kg',
                'description' => "Épicéa format 20cm en sacs de 25kg. Bûchettes parfaites pour petit chauffage. Combustion rapide et efficace. Manipulation très facile.",
                'short_description' => 'Épicéa 20cm bûchettes, manipulation facile',
                'wood_type' => 'epicea',
                'usage_type' => 'chauffage',
                'humidity_rate' => 21.8,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 5.20,
                'stock_quantity' => 80,
                'min_order_quantity' => 5,
                'alert_stock_level' => 15,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Épicéa Bûchettes 15cm - Allumage Parfumé',
                'slug' => 'epicea-buchettes-15cm-allumage-parfume',
                'description' => "Petites bûchettes épicéa 15cm pour allumage parfumé. Sacs de 20kg. Résine naturelle pour démarrage facile. Parfum agréable dès l'allumage.",
                'short_description' => 'Épicéa 15cm allumage, parfum agréable',
                'wood_type' => 'epicea',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 4.80,
                'stock_quantity' => 110,
                'min_order_quantity' => 6,
                'alert_stock_level' => 20,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Épicéa 33cm - Stère Économique',
                'slug' => 'epicea-33cm-stere-economique',
                'description' => "Épicéa en stère format 33cm. Solution économique pour grand foyer. Combustion vive et parfumée. Excellent pour chauffage d'appoint rapide.",
                'short_description' => 'Épicéa 33cm stère, chauffage rapide',
                'wood_type' => 'epicea',
                'usage_type' => 'chauffage',
                'humidity_rate' => 23.0,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 62.00,
                'stock_quantity' => 20,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Épicéa Mix Tailles - Palette Starter',
                'slug' => 'epicea-mix-tailles-palette-starter',
                'description' => "Mélange épicéa différentes tailles sur palette. Pack complet pour débutants. Copeaux + bûchettes + bûches. Solution pratique économique.",
                'short_description' => 'Épicéa mix starter, pack complet',
                'wood_type' => 'epicea',
                'usage_type' => 'chauffage',
                'humidity_rate' => 22.5,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 78.00,
                'stock_quantity' => 28,
                'min_order_quantity' => 1,
                'alert_stock_level' => 6,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Épicéa Premium Sec - Sacs 35kg',
                'slug' => 'epicea-premium-sec-sacs-35kg',
                'description' => "Épicéa premium bien sec en sacs de 35kg. Qualité supérieure pour un résineux. Moins d'humidité, combustion plus régulière. Stock limité.",
                'short_description' => 'Épicéa premium sec, qualité supérieure',
                'wood_type' => 'epicea',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.0,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 7.20,
                'stock_quantity' => 50,
                'min_order_quantity' => 3,
                'alert_stock_level' => 10,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Big Bag Épicéa Économique - 1000kg',
                'slug' => 'big-bag-epicea-economique-1000kg',
                'description' => "Épicéa en big bag 1000kg pour gros volumes. Solution ultra-économique. Livraison avec grue. Parfait pour chauffage d'appoint intensif.",
                'short_description' => 'Épicéa big bag 1000kg, ultra-économique',
                'wood_type' => 'epicea',
                'usage_type' => 'chauffage',
                'humidity_rate' => 24.0,
                'conditioning' => 'big_bags',
                'unit_type' => 'sac',
                'price_per_unit' => 195.00,
                'professional_price' => 175.00,
                'stock_quantity' => 12,
                'min_order_quantity' => 1,
                'alert_stock_level' => 3,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Épicéa Copeaux - Sacs 12kg',
                'slug' => 'epicea-copeaux-sacs-12kg',
                'description' => "Copeaux d'épicéa pour allumage instantané. Sacs de 12kg très pratiques. Parfum intense de résine. S'enflamment immédiatement.",
                'short_description' => 'Copeaux épicéa, allumage instantané',
                'wood_type' => 'epicea',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 3.90,
                'stock_quantity' => 150,
                'min_order_quantity' => 8,
                'alert_stock_level' => 30,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Épicéa 35cm Chauffage Central',
                'slug' => 'epicea-35cm-chauffage-central',
                'description' => "Épicéa format 35cm pour chaudières bois économiques. Combustion rapide et efficace. Prix très attractif pour chauffage central d'appoint.",
                'short_description' => 'Épicéa 35cm chauffage central économique',
                'wood_type' => 'epicea',
                'usage_type' => 'chauffage',
                'humidity_rate' => 22.8,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 85.00,
                'professional_price' => 78.00,
                'stock_quantity' => 25,
                'min_order_quantity' => 1,
                'alert_stock_level' => 5,
                'category_id' => $chauffageCategory->id,
            ],
        ];
        $this->createProducts($epiceaProducts);

        // BOULEAU - 10 produits (bois blanc original)
        $bouleauProducts = [
            [
                'name' => 'Bouleau 30cm - Palette Premium',
                'slug' => 'bouleau-30cm-palette-premium',
                'description' => "Bouleau premium en palette, format 30cm. Écorce blanche caractéristique. Excellent bois de transition entre résineux et feuillus. Combustion régulière.",
                'short_description' => 'Bouleau premium, belles flammes dorées',
                'wood_type' => 'bouleau',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.8,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 82.00,
                'professional_price' => 76.00,
                'stock_quantity' => 25,
                'min_order_quantity' => 1,
                'alert_stock_level' => 5,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Bouleau 25cm - Sacs 25kg',
                'slug' => 'bouleau-25cm-sacs-25kg',
                'description' => "Bouleau en sacs de 25kg, format 25cm. Bois blanc aux propriétés intéressantes. Combustion propre et régulière. Excellent pour les poêles modernes.",
                'short_description' => 'Bouleau blanc, combustion propre',
                'wood_type' => 'bouleau',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.2,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 6.80,
                'stock_quantity' => 60,
                'min_order_quantity' => 3,
                'alert_stock_level' => 12,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Bouleau 33cm - Stère Scandinave',
                'slug' => 'bouleau-33cm-stere-scandinave',
                'description' => "Bouleau en stère format 33cm, style scandinave. Bois blanc nordique de qualité. Combustion avec belles flammes dorées. Esthétique et efficace.",
                'short_description' => 'Bouleau scandinave 33cm, style nordique',
                'wood_type' => 'bouleau',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.0,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 88.00,
                'professional_price' => 82.00,
                'stock_quantity' => 18,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Bouleau 20cm - Sacs 40kg',
                'slug' => 'bouleau-20cm-sacs-40kg',
                'description' => "Bouleau format 20cm en sacs de 40kg. Bûchettes blanches pour poêles modernes. Combustion très propre avec peu de cendres. Manipulation facile.",
                'short_description' => 'Bouleau 20cm, peu de cendres',
                'wood_type' => 'bouleau',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.5,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 7.50,
                'stock_quantity' => 70,
                'min_order_quantity' => 4,
                'alert_stock_level' => 14,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Bouleau Bûchettes 15cm - Allumage Blanc',
                'slug' => 'bouleau-buchettes-15cm-allumage-blanc',
                'description' => "Petites bûchettes bouleau 15cm pour allumage décoratif. Sacs de 20kg. Écorce blanche caractéristique. Allumage facile et esthétique.",
                'short_description' => 'Bouleau 15cm allumage décoratif',
                'wood_type' => 'bouleau',
                'usage_type' => 'chauffage',
                'humidity_rate' => 21.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 6.20,
                'stock_quantity' => 85,
                'min_order_quantity' => 5,
                'alert_stock_level' => 15,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Bouleau 35cm Chauffage Central',
                'slug' => 'bouleau-35cm-chauffage-central',
                'description' => "Bouleau format 35cm pour chaudières bois. Combustion propre pour chauffage central. Peu de résidus. Excellent pour systèmes automatiques.",
                'short_description' => 'Bouleau 35cm chauffage central propre',
                'wood_type' => 'bouleau',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.5,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 95.00,
                'professional_price' => 88.00,
                'stock_quantity' => 22,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Bouleau Mix Nordique - Palette',
                'slug' => 'bouleau-mix-nordique-palette',
                'description' => "Mélange bouleau style nordique sur palette. Différentes tailles pour usage varié. Esthétique scandinave. Combustion propre et décorative.",
                'short_description' => 'Bouleau mix nordique, esthétique scandinave',
                'wood_type' => 'bouleau',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.8,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 92.00,
                'professional_price' => 85.00,
                'stock_quantity' => 20,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Big Bag Bouleau Pro - 800kg',
                'slug' => 'big-bag-bouleau-pro-800kg',
                'description' => "Bouleau professionnel en big bag 800kg. Pour spas, saunas et chauffage propre. Livraison avec grue. Combustion très propre professionnelle.",
                'short_description' => 'Bouleau pro 800kg, spas et saunas',
                'wood_type' => 'bouleau',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.5,
                'conditioning' => 'big_bags',
                'unit_type' => 'sac',
                'price_per_unit' => 285.00,
                'professional_price' => 258.00,
                'stock_quantity' => 8,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'is_professional_only' => true,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Bouleau Premium XL 40cm',
                'slug' => 'bouleau-premium-xl-40cm',
                'description' => "Bouleau premium grande longueur 40cm. Pour très grandes cheminées d'agrément. Combustion longue et décorative. Produit exclusif stock limité.",
                'short_description' => 'Bouleau premium XL 40cm, grandes cheminées',
                'wood_type' => 'bouleau',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.0,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 118.00,
                'professional_price' => 108.00,
                'stock_quantity' => 6,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Bouleau Déco Écorce - Sacs 30kg',
                'slug' => 'bouleau-deco-ecorce-sacs-30kg',
                'description' => "Bouleau décoratif avec écorce blanche préservée. Sacs de 30kg. Pour cheminées d'agrément. Effet visuel unique. Combustion esthétique.",
                'short_description' => 'Bouleau déco écorce blanche, effet unique',
                'wood_type' => 'bouleau',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.8,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 8.90,
                'stock_quantity' => 40,
                'min_order_quantity' => 3,
                'alert_stock_level' => 8,
                'category_id' => $chauffageCategory->id,
            ],
        ];
        $this->createProducts($bouleauProducts);
    }
}