<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class LastWoodTypesSeeder extends Seeder
{
    private function createProducts($products)
    {
        foreach ($products as $productData) {
            $productData['status'] = 'active';
            $product = Product::create($productData);
            
            ProductImage::create([
                'product_id' => $product->id,
                'image_url' => '/storage/images/products/' . $product->slug . '-1.jpg',
                'alt_text' => $product->name . ' - Image principale',
                'sort_order' => 1,
                'is_primary' => true
            ]);
        }
    }

    public function run(): void
    {
        $chauffageCategory = Category::where('slug', 'bois-de-chauffage')->first();
        $cuissonCategory = Category::where('slug', 'bois-de-cuisson')->first();

        // MÉLANGE - 12 produits (solutions mixtes)
        $melangeProducts = [
            [
                'name' => 'Mélange Feuillus 25cm - Palette',
                'slug' => 'melange-feuillus-25cm-palette',
                'description' => "Mélange équilibré de feuillus (chêne, hêtre, charme) en bûches 25cm. Excellent rapport qualité-prix. Combustion efficace et régulière.",
                'short_description' => 'Mélange chêne/hêtre/charme 25cm',
                'wood_type' => 'melange',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.0,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 110.00,
                'professional_price' => 95.00,
                'stock_quantity' => 25,
                'min_order_quantity' => 1,
                'alert_stock_level' => 5,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Mélange Économique - Sacs 40kg',
                'slug' => 'melange-economique-sacs-40kg',
                'description' => "Mélange économique de différentes essences en sacs 40kg. Solution abordable pour chauffage quotidien. Composition variable selon arrivages.",
                'short_description' => 'Mélange économique, bon rapport qualité-prix',
                'wood_type' => 'melange',
                'usage_type' => 'chauffage',
                'humidity_rate' => 22.0,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 6.50,
                'stock_quantity' => 200,
                'min_order_quantity' => 5,
                'alert_stock_level' => 40,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Mélange Premium 30cm - Stère',
                'slug' => 'melange-premium-30cm-stere',
                'description' => "Mélange premium de bois nobles en stère 30cm. Sélection chêne, hêtre, charme de qualité. Combustion longue et régulière. Excellent pouvoir calorifique.",
                'short_description' => 'Mélange premium bois nobles, combustion longue',
                'wood_type' => 'melange',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.2,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 82.00,
                'professional_price' => 75.00,
                'stock_quantity' => 30,
                'min_order_quantity' => 1,
                'alert_stock_level' => 6,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Mélange Démarrage - Sacs 25kg',
                'slug' => 'melange-demarrage-sacs-25kg',
                'description' => "Mélange spécial démarrage avec résineux et feuillus. Sacs de 25kg. Allumage facile puis combustion durable. Solution complète débutants.",
                'short_description' => 'Mélange démarrage, solution débutants',
                'wood_type' => 'melange',
                'usage_type' => 'chauffage',
                'humidity_rate' => 21.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 5.80,
                'stock_quantity' => 120,
                'min_order_quantity' => 6,
                'alert_stock_level' => 25,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Mélange 4 Saisons - Palette Mix',
                'slug' => 'melange-4-saisons-palette-mix',
                'description' => "Mélange 4 saisons sur palette. Adaptation selon période. Résineux hiver, feuillus mi-saison. Composition optimisée toute l'année.",
                'short_description' => 'Mélange 4 saisons, optimisé toute année',
                'wood_type' => 'melange',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.8,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 98.00,
                'professional_price' => 89.00,
                'stock_quantity' => 35,
                'min_order_quantity' => 1,
                'alert_stock_level' => 7,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Big Bag Mélange Pro - 1100kg',
                'slug' => 'big-bag-melange-pro-1100kg',
                'description' => "Mélange professionnel en big bag 1100kg. Composition équilibrée pour gros consommateurs. Livraison avec grue. Prix dégressifs pros.",
                'short_description' => 'Mélange pro 1100kg, gros consommateurs',
                'wood_type' => 'melange',
                'usage_type' => 'chauffage',
                'humidity_rate' => 21.0,
                'conditioning' => 'big_bags',
                'unit_type' => 'sac',
                'price_per_unit' => 245.00,
                'professional_price' => 220.00,
                'stock_quantity' => 15,
                'min_order_quantity' => 1,
                'alert_stock_level' => 3,
                'is_professional_only' => true,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Mélange Chauffage Central 35cm',
                'slug' => 'melange-chauffage-central-35cm',
                'description' => "Mélange optimisé format 35cm pour chauffage central. Combustion régulière et efficace. Bon rendement énergétique. Livré sur palette.",
                'short_description' => 'Mélange 35cm chauffage central optimisé',
                'wood_type' => 'melange',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.5,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 105.00,
                'professional_price' => 96.00,
                'stock_quantity' => 25,
                'min_order_quantity' => 1,
                'alert_stock_level' => 5,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Mélange Cuisson BBQ - Sacs 30kg',
                'slug' => 'melange-cuisson-bbq-sacs-30kg',
                'description' => "Mélange spécial barbecue et cuisson. Fruitiers, hêtre, chêne. Arômes variés pour grillades. Sans traitement chimique. Perfect pour BBQ.",
                'short_description' => 'Mélange BBQ, arômes variés grillades',
                'wood_type' => 'melange',
                'usage_type' => 'cuisson',
                'humidity_rate' => 17.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 10.90,
                'stock_quantity' => 80,
                'min_order_quantity' => 3,
                'alert_stock_level' => 15,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Mélange Bûchettes 15cm - Allumage',
                'slug' => 'melange-buchettes-15cm-allumage',
                'description' => "Mélange bûchettes 15cm pour allumage universel. Sacs de 20kg. Résineux et feuillus mélangés. Démarrage garanti tous feux.",
                'short_description' => 'Mélange bûchettes, allumage universel',
                'wood_type' => 'melange',
                'usage_type' => 'chauffage',
                'humidity_rate' => 21.8,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 5.20,
                'stock_quantity' => 140,
                'min_order_quantity' => 8,
                'alert_stock_level' => 25,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Mélange Premium XL 45cm',
                'slug' => 'melange-premium-xl-45cm',
                'description' => "Mélange premium grande longueur 45cm. Sélection bois nobles grandes tailles. Pour très grandes cheminées. Combustion exceptionnelle.",
                'short_description' => 'Mélange premium XL 45cm, bois nobles',
                'wood_type' => 'melange',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.8,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 125.00,
                'professional_price' => 115.00,
                'stock_quantity' => 8,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Mélange Région - Palette Locale',
                'slug' => 'melange-region-palette-locale',
                'description' => "Mélange d'essences locales sur palette. Composition selon disponibilité régionale. Circuit court. Soutien forêt locale. Prix solidaire.",
                'short_description' => 'Mélange local, circuit court solidaire',
                'wood_type' => 'melange',
                'usage_type' => 'chauffage',
                'humidity_rate' => 21.2,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 88.00,
                'professional_price' => 82.00,
                'stock_quantity' => 40,
                'min_order_quantity' => 1,
                'alert_stock_level' => 8,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Mélange Super Économique - Sacs 50kg',
                'slug' => 'melange-super-economique-sacs-50kg',
                'description' => "Mélange super économique en gros sacs 50kg. Solution budget pour chauffage quotidien. Composition variable. Prix imbattable.",
                'short_description' => 'Mélange super économique, prix imbattable',
                'wood_type' => 'melange',
                'usage_type' => 'chauffage',
                'humidity_rate' => 23.5,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 7.80,
                'stock_quantity' => 180,
                'min_order_quantity' => 4,
                'alert_stock_level' => 35,
                'category_id' => $chauffageCategory->id,
            ],
        ];
        $this->createProducts($melangeProducts);

        // FRÊNE - 10 produits (bois noble)
        $fresneProducts = [
            [
                'name' => 'Frêne 30cm - Stère Premium',
                'slug' => 'fresne-30cm-stere-premium',
                'description' => "Frêne premium en stère, format 30cm. Bois noble avec excellent pouvoir calorifique. Combustion vive et régulière. Parfait pour chauffage principal.",
                'short_description' => 'Frêne premium, combustion vive',
                'wood_type' => 'fresne',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.2,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 82.00,
                'professional_price' => 75.00,
                'stock_quantity' => 18,
                'min_order_quantity' => 1,
                'alert_stock_level' => 3,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Frêne 25cm - Sacs 40kg',
                'slug' => 'fresne-25cm-sacs-40kg',
                'description' => "Frêne en sacs de 40kg, format 25cm. Bois clair aux veines marquées. Combustion vive et efficace. Excellent pour poêles modernes haute performance.",
                'short_description' => 'Frêne 25cm veines marquées, haute performance',
                'wood_type' => 'fresne',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.0,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 8.90,
                'professional_price' => 8.20,
                'stock_quantity' => 55,
                'min_order_quantity' => 4,
                'alert_stock_level' => 12,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Frêne 33cm - Palette Noble',
                'slug' => 'fresne-33cm-palette-noble',
                'description' => "Frêne noble en palette format 33cm. Bois de qualité supérieure. Combustion longue et régulière. Pour chauffage haut de gamme. Livré palette filmée.",
                'short_description' => 'Frêne noble 33cm, chauffage haut de gamme',
                'wood_type' => 'fresne',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.5,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 115.00,
                'professional_price' => 105.00,
                'stock_quantity' => 15,
                'min_order_quantity' => 1,
                'alert_stock_level' => 3,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Frêne 20cm - Sacs 25kg',
                'slug' => 'fresne-20cm-sacs-25kg',
                'description' => "Frêne format 20cm en sacs de 25kg. Bûchettes nobles pour petits foyers. Combustion vive et propre. Manipulation facile. Idéal poêles design.",
                'short_description' => 'Frêne 20cm bûchettes nobles, poêles design',
                'wood_type' => 'fresne',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 7.20,
                'stock_quantity' => 45,
                'min_order_quantity' => 4,
                'alert_stock_level' => 10,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Frêne 35cm Chauffage Central',
                'slug' => 'fresne-35cm-chauffage-central',
                'description' => "Frêne format 35cm pour chaudières bois haut rendement. Combustion optimisée. Excellent pouvoir calorifique. Parfait chauffage central premium.",
                'short_description' => 'Frêne 35cm chauffage central premium',
                'wood_type' => 'fresne',
                'usage_type' => 'chauffage',
                'humidity_rate' => 17.8,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 125.00,
                'professional_price' => 115.00,
                'stock_quantity' => 12,
                'min_order_quantity' => 1,
                'alert_stock_level' => 3,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Frêne Bûchettes 15cm - Allumage Noble',
                'slug' => 'fresne-buchettes-15cm-allumage-noble',
                'description' => "Petites bûchettes frêne 15cm pour allumage noble. Sacs de 20kg. Prennent feu facilement. Excellent pour démarrer avec du bois de qualité.",
                'short_description' => 'Frêne 15cm allumage noble, qualité',
                'wood_type' => 'fresne',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 6.80,
                'stock_quantity' => 60,
                'min_order_quantity' => 5,
                'alert_stock_level' => 12,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Big Bag Frêne Pro - 900kg',
                'slug' => 'big-bag-fresne-pro-900kg',
                'description' => "Frêne professionnel en big bag 900kg. Pour gros consommateurs exigeants. Qualité constante. Livraison avec grue. Prix dégressifs pros.",
                'short_description' => 'Frêne pro 900kg, consommateurs exigeants',
                'wood_type' => 'fresne',
                'usage_type' => 'chauffage',
                'humidity_rate' => 17.5,
                'conditioning' => 'big_bags',
                'unit_type' => 'sac',
                'price_per_unit' => 315.00,
                'professional_price' => 285.00,
                'stock_quantity' => 6,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'is_professional_only' => true,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Frêne Premium XL 45cm',
                'slug' => 'fresne-premium-xl-45cm',
                'description' => "Frêne premium grande longueur 45cm. Pour très grandes cheminées premium. Combustion exceptionnellement longue. Produit exclusif stock très limité.",
                'short_description' => 'Frêne premium XL 45cm, très grandes cheminées',
                'wood_type' => 'fresne',
                'usage_type' => 'chauffage',
                'humidity_rate' => 17.0,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 135.00,
                'professional_price' => 125.00,
                'stock_quantity' => 4,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Frêne Cuisson - Sacs 30kg',
                'slug' => 'fresne-cuisson-sacs-30kg',
                'description' => "Frêne spécial cuisson en sacs de 30kg. Combustion douce et régulière. Parfait pour grillades délicates. Goût neutre. Sans traitement chimique.",
                'short_description' => 'Frêne cuisson douce, grillades délicates',
                'wood_type' => 'fresne',
                'usage_type' => 'cuisson',
                'humidity_rate' => 16.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 11.90,
                'stock_quantity' => 35,
                'min_order_quantity' => 2,
                'alert_stock_level' => 8,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Frêne Mix Premium - Palette',
                'slug' => 'fresne-mix-premium-palette',
                'description' => "Mélange frêne différentes tailles sur palette premium. Solution complète haut de gamme. Combustion variée optimisée. Stock exclusif limité.",
                'short_description' => 'Frêne mix premium, solution haut de gamme',
                'wood_type' => 'fresne',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.8,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 108.00,
                'professional_price' => 98.00,
                'stock_quantity' => 10,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'category_id' => $chauffageCategory->id,
            ],
        ];
        $this->createProducts($fresneProducts);
    }
}