<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class MegaProductCatalogSeeder extends Seeder
{
    private function createProducts($products)
    {
        foreach ($products as $productData) {
            $productData['status'] = 'active';
            $product = Product::create($productData);
            
            ProductImage::create([
                'product_id' => $product->id,
                'image_url' => '/storage/images/products/' . $product->slug . '-1.jpg',
                'alt_text' => $product->name . ' - Image principale',
                'sort_order' => 1,
                'is_primary' => true
            ]);
        }
    }

    public function run(): void
    {
        $chauffageCategory = Category::where('slug', 'bois-de-chauffage')->first();
        $cuissonCategory = Category::where('slug', 'bois-de-cuisson')->first();

        // Vider les produits existants de façon sécurisée
        ProductImage::query()->delete();
        Product::query()->delete();

        // CHÊNE - 12 produits (essence premium)
        $cheneProducts = [
            [
                'name' => 'Chêne Premium 33cm - Stère',
                'slug' => 'chene-premium-33cm-stere',
                'description' => "Chêne de première qualité, séché naturellement pendant 24 mois minimum. Taux d'humidité inférieur à 20%. Excellent pouvoir calorifique de 4,2 kWh/kg. Combustion lente et régulière, parfait pour les longues soirées d'hiver.",
                'short_description' => 'Chêne premium séché 24 mois, excellent pouvoir calorifique',
                'wood_type' => 'chene',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.5,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 85.00,
                'professional_price' => 78.00,
                'stock_quantity' => 45,
                'min_order_quantity' => 1,
                'alert_stock_level' => 5,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Chêne 30cm Four à Pizza',
                'slug' => 'chene-30cm-four-pizza',
                'description' => "Chêne spécialement sélectionné pour la cuisson au feu de bois. Bûches de 30cm parfaites pour four à pizza traditionnel. Montée en température rapide et combustion intense.",
                'short_description' => 'Chêne 30cm spécial four à pizza, goût authentique',
                'wood_type' => 'chene',
                'usage_type' => 'cuisson',
                'humidity_rate' => 16.5,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 95.00,
                'professional_price' => 85.00,
                'stock_quantity' => 15,
                'min_order_quantity' => 1,
                'alert_stock_level' => 3,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Chêne 25cm - Sacs 40kg Premium',
                'slug' => 'chene-25cm-sacs-40kg-premium',
                'description' => "Chêne sec en sacs pratiques de 40kg. Format 25cm idéal pour poêles et inserts. Excellent rapport qualité-prix pour du chêne premium. Sacs étanches pour préserver la qualité.",
                'short_description' => 'Chêne 25cm premium en sacs pratiques 40kg',
                'wood_type' => 'chene',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.0,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 9.50,
                'professional_price' => 8.80,
                'stock_quantity' => 100,
                'min_order_quantity' => 3,
                'alert_stock_level' => 15,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Chêne 20cm - Sacs 25kg',
                'slug' => 'chene-20cm-sacs-25kg',
                'description' => "Chêne en bûchettes de 20cm, parfait pour petits foyers. Sacs de 25kg faciles à manipuler. Qualité chêne premium en format réduit. Idéal pour poêles de petite taille.",
                'short_description' => 'Chêne 20cm en bûchettes, sacs 25kg',
                'wood_type' => 'chene',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 7.20,
                'professional_price' => 6.50,
                'stock_quantity' => 80,
                'min_order_quantity' => 4,
                'alert_stock_level' => 12,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Chêne 40cm - Palette Grande Longueur',
                'slug' => 'chene-40cm-palette-grande-longueur',
                'description' => "Chêne en grande longueur 40cm sur palette. Pour grandes cheminées et inserts XXL. Combustion exceptionnellement longue. Livré sur palette sécurisée (≈1,6 stère).",
                'short_description' => 'Chêne 40cm grande longueur sur palette',
                'wood_type' => 'chene',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.0,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 135.00,
                'professional_price' => 125.00,
                'stock_quantity' => 18,
                'min_order_quantity' => 1,
                'alert_stock_level' => 3,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Big Bag Chêne Pro - 1200kg',
                'slug' => 'big-bag-chene-pro-1200kg',
                'description' => "Solution professionnelle premium en big bag de 1200kg. Chêne de qualité supérieure pour professionnels. Livraison avec grue obligatoire. Prix dégressifs dès 3 big bags.",
                'short_description' => 'Solution pro 1200kg chêne premium',
                'wood_type' => 'chene',
                'usage_type' => 'chauffage',
                'humidity_rate' => 17.5,
                'conditioning' => 'big_bags',
                'unit_type' => 'sac',
                'price_per_unit' => 380.00,
                'professional_price' => 340.00,
                'stock_quantity' => 8,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'is_professional_only' => true,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Chêne Fumage Barbecue 25cm',
                'slug' => 'chene-fumage-barbecue-25cm',
                'description' => "Chêne spécial barbecue et fumage. Bûches de 25cm parfaites pour grills et fumoirs. Arôme boisé intense. Sans traitement chimique. Combustion lente pour fumage long.",
                'short_description' => 'Chêne fumage barbecue, arôme boisé intense',
                'wood_type' => 'chene',
                'usage_type' => 'cuisson',
                'humidity_rate' => 16.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 13.50,
                'stock_quantity' => 40,
                'min_order_quantity' => 2,
                'alert_stock_level' => 8,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Chêne Mixte 30cm - Stère Économique',
                'slug' => 'chene-mixte-30cm-stere-economique',
                'description' => "Chêne qualité standard en stère. Mélange de chêne jeune et mature. Bon rapport qualité-prix. Parfait pour chauffage quotidien. Séchage 18 mois minimum.",
                'short_description' => 'Chêne économique, bon rapport qualité-prix',
                'wood_type' => 'chene',
                'usage_type' => 'chauffage',
                'humidity_rate' => 21.0,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 75.00,
                'professional_price' => 68.00,
                'stock_quantity' => 60,
                'min_order_quantity' => 1,
                'alert_stock_level' => 8,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Chêne Bûchettes 15cm - Sacs 20kg',
                'slug' => 'chene-buchettes-15cm-sacs-20kg',
                'description' => "Petites bûchettes de chêne 15cm en sacs de 20kg. Idéal pour allumage et maintien de feu. Format pratique pour manutention facile. Parfait complément aux grosses bûches.",
                'short_description' => 'Bûchettes chêne 15cm pour allumage',
                'wood_type' => 'chene',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 6.80,
                'stock_quantity' => 120,
                'min_order_quantity' => 5,
                'alert_stock_level' => 20,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Chêne Chauffage Central - Palette 35cm',
                'slug' => 'chene-chauffage-central-palette-35cm',
                'description' => "Chêne format 35cm spécial chauffage central. Bûches calibrées pour chaudières bois. Combustion optimisée pour rendement maximum. Livré sur palette filmée.",
                'short_description' => 'Chêne 35cm spécial chauffage central',
                'wood_type' => 'chene',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.5,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 128.00,
                'professional_price' => 118.00,
                'stock_quantity' => 22,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Chêne Restaurant Pro - Stère 28cm',
                'slug' => 'chene-restaurant-pro-stere-28cm',
                'description' => "Chêne professionnel format 28cm pour restaurants. Calibrage précis pour fours professionnels. Combustion régulière et propre. Livraison rapide pour professionnels.",
                'short_description' => 'Chêne pro 28cm pour restaurants',
                'wood_type' => 'chene',
                'usage_type' => 'cuisson',
                'humidity_rate' => 15.5,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 105.00,
                'professional_price' => 92.00,
                'stock_quantity' => 12,
                'min_order_quantity' => 2,
                'alert_stock_level' => 3,
                'is_professional_only' => true,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Chêne Premium XL - Gros Stères 50cm',
                'slug' => 'chene-premium-xl-gros-steres-50cm',
                'description' => "Chêne premium en très grande longueur 50cm. Pour très grandes cheminées et foyers monumentaux. Combustion exceptionnelle de plusieurs heures. Produit rare et exclusif.",
                'short_description' => 'Chêne premium XL 50cm, très grandes cheminées',
                'wood_type' => 'chene',
                'usage_type' => 'chauffage',
                'humidity_rate' => 17.0,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 145.00,
                'professional_price' => 135.00,
                'stock_quantity' => 6,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'category_id' => $chauffageCategory->id,
            ],
        ];

        // Créer tous les produits Chêne
        $this->createProducts($cheneProducts);

        // HÊTRE - 12 produits (essence populaire)
        $hetreProducts = [
            [
                'name' => 'Hêtre Premium 33cm - Stère',
                'slug' => 'hetre-premium-33cm-stere',
                'description' => "Hêtre de première qualité en stère. Combustion régulière avec de belles flammes et chaleur constante. Excellent pour poêles à bois et inserts. Séché naturellement 20 mois.",
                'short_description' => 'Hêtre premium 33cm, combustion régulière',
                'wood_type' => 'hetre',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.8,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 78.00,
                'professional_price' => 72.00,
                'stock_quantity' => 35,
                'min_order_quantity' => 1,
                'alert_stock_level' => 5,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Hêtre 25cm - Sacs 40kg',
                'slug' => 'hetre-25cm-sacs-40kg',
                'description' => "Hêtre sec en sacs pratiques de 40kg. Format 25cm idéal pour poêles et inserts. Conditionnement étanche pour préserver la qualité. Facile à manipuler et à stocker.",
                'short_description' => 'Hêtre 25cm en sacs pratiques 40kg',
                'wood_type' => 'hetre',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.2,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 8.50,
                'professional_price' => 7.80,
                'stock_quantity' => 120,
                'min_order_quantity' => 5,
                'alert_stock_level' => 20,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Big Bag Hêtre Pro - 1000kg',
                'slug' => 'big-bag-hetre-pro-1000kg',
                'description' => "Solution professionnelle en big bag de 1000kg pour restaurants et pizzerias. Hêtre premium pour cuisson professionnelle. Livraison avec grue.",
                'short_description' => 'Solution pro 1000kg, livraison avec grue',
                'wood_type' => 'hetre',
                'usage_type' => 'both',
                'humidity_rate' => 18.0,
                'conditioning' => 'big_bags',
                'unit_type' => 'sac',
                'price_per_unit' => 320.00,
                'professional_price' => 280.00,
                'stock_quantity' => 12,
                'min_order_quantity' => 2,
                'alert_stock_level' => 3,
                'is_professional_only' => true,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Hêtre 30cm - Palette Standard',
                'slug' => 'hetre-30cm-palette-standard',
                'description' => "Hêtre en palette format 30cm. Excellent rapport qualité-prix. Combustion vive et régulière. Parfait pour un chauffage d'appoint. Environ 1,4 stère par palette.",
                'short_description' => 'Hêtre 30cm palette, bon rapport qualité-prix',
                'wood_type' => 'hetre',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.5,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 105.00,
                'professional_price' => 95.00,
                'stock_quantity' => 28,
                'min_order_quantity' => 1,
                'alert_stock_level' => 5,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Hêtre 20cm - Sacs 25kg',
                'slug' => 'hetre-20cm-sacs-25kg',
                'description' => "Hêtre en bûchettes de 20cm, sacs de 25kg. Format parfait pour petits poêles. Combustion rapide et efficace. Facile à manipuler. Idéal pour allumage et maintien.",
                'short_description' => 'Hêtre 20cm bûchettes, sacs 25kg',
                'wood_type' => 'hetre',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 6.80,
                'stock_quantity' => 90,
                'min_order_quantity' => 4,
                'alert_stock_level' => 15,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Hêtre Pizza 28cm - Stère Cuisson',
                'slug' => 'hetre-pizza-28cm-stere-cuisson',
                'description' => "Hêtre spécial cuisson format 28cm. Calibrage précis pour fours à pizza. Combustion vive et régulière. Montée en température rapide. Parfait pour pizzerias.",
                'short_description' => 'Hêtre 28cm spécial pizza, combustion vive',
                'wood_type' => 'hetre',
                'usage_type' => 'cuisson',
                'humidity_rate' => 17.5,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 88.00,
                'professional_price' => 78.00,
                'stock_quantity' => 18,
                'min_order_quantity' => 1,
                'alert_stock_level' => 3,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Hêtre Économique Mix - Palette',
                'slug' => 'hetre-economique-mix-palette',
                'description' => "Mélange hêtre différentes tailles sur palette. Solution économique pour chauffage quotidien. Combustion efficace. Bon rapport qualité-prix pour usage régulier.",
                'short_description' => 'Hêtre économique mix, usage quotidien',
                'wood_type' => 'hetre',
                'usage_type' => 'chauffage',
                'humidity_rate' => 21.0,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 88.00,
                'professional_price' => 80.00,
                'stock_quantity' => 40,
                'min_order_quantity' => 1,
                'alert_stock_level' => 8,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Hêtre 35cm Chauffage Central',
                'slug' => 'hetre-35cm-chauffage-central',
                'description' => "Hêtre format 35cm pour chaudières bois. Calibrage précis pour chauffage central. Combustion optimisée. Rendement énergétique maximum. Livré sur palette.",
                'short_description' => 'Hêtre 35cm chauffage central, rendement max',
                'wood_type' => 'hetre',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.5,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 115.00,
                'professional_price' => 105.00,
                'stock_quantity' => 20,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Hêtre Bûchettes 15cm Allumage',
                'slug' => 'hetre-buchettes-15cm-allumage',
                'description' => "Petites bûchettes hêtre 15cm pour allumage. Sacs de 20kg faciles à porter. Prennent feu rapidement. Complément idéal aux grosses bûches. Stock toujours disponible.",
                'short_description' => 'Bûchettes hêtre 15cm allumage facile',
                'wood_type' => 'hetre',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 5.90,
                'stock_quantity' => 150,
                'min_order_quantity' => 6,
                'alert_stock_level' => 25,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Hêtre Restaurant Pro 26cm',
                'slug' => 'hetre-restaurant-pro-26cm',
                'description' => "Hêtre professionnel format 26cm pour restaurants. Calibrage très précis. Combustion constante et prévisible. Livraison rapide pour professionnels. Prix dégressifs.",
                'short_description' => 'Hêtre pro 26cm restaurants, calibrage précis',
                'wood_type' => 'hetre',
                'usage_type' => 'cuisson',
                'humidity_rate' => 16.8,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 92.00,
                'professional_price' => 82.00,
                'stock_quantity' => 15,
                'min_order_quantity' => 2,
                'alert_stock_level' => 3,
                'is_professional_only' => true,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Hêtre Premium XL 45cm',
                'slug' => 'hetre-premium-xl-45cm',
                'description' => "Hêtre premium grande longueur 45cm. Pour très grandes cheminées. Combustion exceptionnellement longue. Produit premium pour foyers d'exception. Stock limité.",
                'short_description' => 'Hêtre premium XL 45cm, très grandes cheminées',
                'wood_type' => 'hetre',
                'usage_type' => 'chauffage',
                'humidity_rate' => 17.2,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 125.00,
                'professional_price' => 115.00,
                'stock_quantity' => 8,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Hêtre Fumage Doux - Sacs 30kg',
                'slug' => 'hetre-fumage-doux-sacs-30kg',
                'description' => "Hêtre spécial fumage en sacs de 30kg. Arôme doux et délicat. Parfait pour fumage à froid et à chaud. Très apprécié pour poissons et volailles. Sans traitement.",
                'short_description' => 'Hêtre fumage doux, arôme délicat',
                'wood_type' => 'hetre',
                'usage_type' => 'cuisson',
                'humidity_rate' => 16.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 11.50,
                'stock_quantity' => 60,
                'min_order_quantity' => 3,
                'alert_stock_level' => 12,
                'category_id' => $cuissonCategory->id,
            ],
        ];

        // Créer tous les produits Hêtre
        $this->createProducts($hetreProducts);

        // CHARME - 10 produits (bois dense)
        $charmeProducts = [
            [
                'name' => 'Charme Premium 30cm - Palette',
                'slug' => 'charme-premium-30cm-palette',
                'description' => "Charme sec sur palette, format 30cm. Bois dense avec excellent pouvoir calorifique. Combustion longue et régulière. Idéal pour maintenir la chaleur toute la nuit.",
                'short_description' => 'Charme dense 30cm, combustion longue',
                'wood_type' => 'charme',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.5,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 115.00,
                'professional_price' => 105.00,
                'stock_quantity' => 20,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Charme 25cm - Sacs 25kg',
                'slug' => 'charme-25cm-sacs-25kg',
                'description' => "Charme en sacs de 25kg, format 25cm. Bois très dense, combustion lente et régulière. Parfait pour les petits foyers. Excellent rapport qualité-prix pour ce bois noble.",
                'short_description' => 'Charme dense en sacs 25kg, combustion lente',
                'wood_type' => 'charme',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 7.90,
                'stock_quantity' => 80,
                'min_order_quantity' => 4,
                'alert_stock_level' => 12,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Charme 33cm - Stère Premium',
                'slug' => 'charme-33cm-stere-premium',
                'description' => "Charme premium en stère format 33cm. Bois noble avec combustion exceptionnelle. Braises durables, chaleur constante. Parfait pour chauffage principal haut de gamme.",
                'short_description' => 'Charme premium 33cm, braises durables',
                'wood_type' => 'charme',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.8,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 88.00,
                'professional_price' => 82.00,
                'stock_quantity' => 25,
                'min_order_quantity' => 1,
                'alert_stock_level' => 5,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Charme 20cm - Sacs 40kg',
                'slug' => 'charme-20cm-sacs-40kg',
                'description' => "Charme format 20cm en sacs de 40kg. Bûchettes idéales pour poêles modernes. Combustion très efficace. Manipulation facile. Stock important toute l'année.",
                'short_description' => 'Charme 20cm bûchettes, très efficace',
                'wood_type' => 'charme',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.8,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 9.20,
                'professional_price' => 8.50,
                'stock_quantity' => 70,
                'min_order_quantity' => 3,
                'alert_stock_level' => 12,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Charme 35cm Chauffage Central',
                'slug' => 'charme-35cm-chauffage-central',
                'description' => "Charme format 35cm pour chaudières bois. Calibrage précis pour chauffage central. Combustion très régulière. Rendement énergétique maximum. Braises persistantes.",
                'short_description' => 'Charme 35cm chauffage central, rendement max',
                'wood_type' => 'charme',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.2,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 125.00,
                'professional_price' => 115.00,
                'stock_quantity' => 15,
                'min_order_quantity' => 1,
                'alert_stock_level' => 3,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Charme Bûchettes 15cm - Allumage',
                'slug' => 'charme-buchettes-15cm-allumage',
                'description' => "Petites bûchettes charme 15cm pour allumage. Sacs de 20kg pratiques. Prennent feu facilement malgré la densité. Excellent pour démarrer avec du bois dur.",
                'short_description' => 'Bûchettes charme 15cm, allumage bois dur',
                'wood_type' => 'charme',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 6.50,
                'stock_quantity' => 90,
                'min_order_quantity' => 5,
                'alert_stock_level' => 15,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Charme Mix Économique - Palette',
                'slug' => 'charme-mix-economique-palette',
                'description' => "Mélange charme différentes tailles sur palette. Solution économique pour profiter des qualités du charme. Combustion efficace. Prix attractif pour ce bois noble.",
                'short_description' => 'Charme mix économique, prix attractif',
                'wood_type' => 'charme',
                'usage_type' => 'chauffage',
                'humidity_rate' => 21.2,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 98.00,
                'professional_price' => 89.00,
                'stock_quantity' => 30,
                'min_order_quantity' => 1,
                'alert_stock_level' => 6,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Big Bag Charme Pro - 800kg',
                'slug' => 'big-bag-charme-pro-800kg',
                'description' => "Charme professionnel en big bag 800kg. Pour gros consommateurs. Livraison avec grue. Qualité constante. Prix dégressifs dès 3 big bags. Idéal restaurants.",
                'short_description' => 'Charme pro 800kg, gros consommateurs',
                'wood_type' => 'charme',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.0,
                'conditioning' => 'big_bags',
                'unit_type' => 'sac',
                'price_per_unit' => 295.00,
                'professional_price' => 265.00,
                'stock_quantity' => 10,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'is_professional_only' => true,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Charme Premium XL 45cm',
                'slug' => 'charme-premium-xl-45cm',
                'description' => "Charme premium grande longueur 45cm. Pour très grandes cheminées et inserts XXL. Combustion exceptionnellement longue. Produit exclusif stock limité.",
                'short_description' => 'Charme premium XL 45cm, très grandes cheminées',
                'wood_type' => 'charme',
                'usage_type' => 'chauffage',
                'humidity_rate' => 17.5,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 135.00,
                'professional_price' => 125.00,
                'stock_quantity' => 6,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Charme Cuisson Lente - Sacs 30kg',
                'slug' => 'charme-cuisson-lente-sacs-30kg',
                'description' => "Charme spécial cuisson lente. Format adapté pour fours et grills. Combustion très progressive. Maintient la température longtemps. Parfait pour cuissons longues.",
                'short_description' => 'Charme cuisson lente, température constante',
                'wood_type' => 'charme',
                'usage_type' => 'cuisson',
                'humidity_rate' => 16.8,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 12.50,
                'stock_quantity' => 50,
                'min_order_quantity' => 2,
                'alert_stock_level' => 10,
                'category_id' => $cuissonCategory->id,
            ],
        ];
        $this->createProducts($charmeProducts);
    }
}