<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class RemainingWoodTypesSeeder extends Seeder
{
    private function createProducts($products)
    {
        foreach ($products as $productData) {
            $productData['status'] = 'active';
            $product = Product::create($productData);
            
            ProductImage::create([
                'product_id' => $product->id,
                'image_url' => '/storage/images/products/' . $product->slug . '-1.jpg',
                'alt_text' => $product->name . ' - Image principale',
                'sort_order' => 1,
                'is_primary' => true
            ]);
        }
    }

    public function run(): void
    {
        $chauffageCategory = Category::where('slug', 'bois-de-chauffage')->first();
        $cuissonCategory = Category::where('slug', 'bois-de-cuisson')->first();

        // BOIS FRUITIERS - 10 produits (spécialité cuisson)
        $fruitiersProducts = [
            [
                'name' => 'Bois Fruitiers Barbecue - Sacs 25kg',
                'slug' => 'bois-fruitiers-barbecue-sacs-25kg',
                'description' => "Mélange de bois fruitiers (pommier, cerisier, prunier) pour barbecue. Arômes délicats, combustion lente et régulière. Peu de fumée. Sans traitement chimique.",
                'short_description' => 'Mélange fruitiers barbecue, arômes délicats',
                'wood_type' => 'fruitiers',
                'usage_type' => 'cuisson',
                'humidity_rate' => 15.8,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 12.90,
                'stock_quantity' => 80,
                'min_order_quantity' => 2,
                'alert_stock_level' => 15,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Fruitiers Premium Mix - Stère',
                'slug' => 'fruitiers-premium-mix-stere',
                'description' => "Mélange premium de bois fruitiers en stère. Excellent pour chauffage d'agrément et cuisson. Parfum délicat qui embaume votre intérieur.",
                'short_description' => 'Mix fruitiers premium, parfum délicat',
                'wood_type' => 'fruitiers',
                'usage_type' => 'both',
                'humidity_rate' => 17.0,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 110.00,
                'professional_price' => 98.00,
                'stock_quantity' => 8,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Fruitiers Fumage - Sacs 20kg',
                'slug' => 'fruitiers-fumage-sacs-20kg',
                'description' => "Bois fruitiers spécialement sélectionnés pour fumage. Copeaux et petites bûches. Arômes subtils pour charcuteries et viandes. Format professionnel.",
                'short_description' => 'Fruitiers fumage, arômes subtils',
                'wood_type' => 'fruitiers',
                'usage_type' => 'cuisson',
                'humidity_rate' => 14.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 16.90,
                'stock_quantity' => 45,
                'min_order_quantity' => 2,
                'alert_stock_level' => 8,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Fruitiers 30cm - Palette Cuisson',
                'slug' => 'fruitiers-30cm-palette-cuisson',
                'description' => "Fruitiers format 30cm sur palette pour fours et grills. Combustion douce et parfumée. Idéal pour pizzerias artisanales. Livraison sur palette filmée.",
                'short_description' => 'Fruitiers 30cm palette, combustion parfumée',
                'wood_type' => 'fruitiers',
                'usage_type' => 'cuisson',
                'humidity_rate' => 16.2,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 145.00,
                'professional_price' => 128.00,
                'stock_quantity' => 12,
                'min_order_quantity' => 1,
                'alert_stock_level' => 3,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Fruitiers Chauffage - Sacs 40kg',
                'slug' => 'fruitiers-chauffage-sacs-40kg',
                'description' => "Bois fruitiers pour chauffage d'agrément. Sacs de 40kg pratiques. Parfum agréable dans la maison. Combustion douce et chaleureuse.",
                'short_description' => 'Fruitiers chauffage, parfum agréable',
                'wood_type' => 'fruitiers',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.5,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 11.50,
                'stock_quantity' => 60,
                'min_order_quantity' => 3,
                'alert_stock_level' => 12,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Fruitiers Restaurant Pro - Stère 28cm',
                'slug' => 'fruitiers-restaurant-pro-stere-28cm',
                'description' => "Fruitiers professionnels format 28cm pour restaurants. Calibrage précis. Arômes constants. Parfait pour cuisine au feu de bois. Livraison prioritaire pros.",
                'short_description' => 'Fruitiers pro 28cm restaurants, arômes constants',
                'wood_type' => 'fruitiers',
                'usage_type' => 'cuisson',
                'humidity_rate' => 15.5,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 125.00,
                'professional_price' => 108.00,
                'stock_quantity' => 10,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'is_professional_only' => true,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Fruitiers Mix Économique - Palette',
                'slug' => 'fruitiers-mix-economique-palette',
                'description' => "Mélange économique fruitiers différentes tailles. Solution abordable pour profiter des arômes fruitiers. Combustion efficace. Prix attractif.",
                'short_description' => 'Fruitiers économique, arômes abordables',
                'wood_type' => 'fruitiers',
                'usage_type' => 'both',
                'humidity_rate' => 19.0,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 125.00,
                'professional_price' => 112.00,
                'stock_quantity' => 18,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Fruitiers Bûchettes 15cm - Allumage',
                'slug' => 'fruitiers-buchettes-15cm-allumage',
                'description' => "Petites bûchettes fruitiers 15cm. Allumage facile avec parfums délicats. Sacs de 20kg. Complément parfait aux gros bois. Prennent feu rapidement.",
                'short_description' => 'Bûchettes fruitiers 15cm, allumage parfumé',
                'wood_type' => 'fruitiers',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 9.80,
                'stock_quantity' => 70,
                'min_order_quantity' => 4,
                'alert_stock_level' => 12,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Big Bag Fruitiers Pro - 600kg',
                'slug' => 'big-bag-fruitiers-pro-600kg',
                'description' => "Fruitiers en big bag 600kg pour professionnels. Restaurants gastronomiques. Qualité constante. Livraison avec grue. Prix dégressifs pros.",
                'short_description' => 'Fruitiers pro 600kg, restaurants gastronomiques',
                'wood_type' => 'fruitiers',
                'usage_type' => 'cuisson',
                'humidity_rate' => 15.0,
                'conditioning' => 'big_bags',
                'unit_type' => 'sac',
                'price_per_unit' => 285.00,
                'professional_price' => 245.00,
                'stock_quantity' => 6,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'is_professional_only' => true,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Fruitiers Premium XL 40cm',
                'slug' => 'fruitiers-premium-xl-40cm',
                'description' => "Fruitiers premium grande longueur 40cm. Pour grandes cheminées d'agrément. Combustion longue et parfumée. Produit exclusif stock très limité.",
                'short_description' => 'Fruitiers premium XL 40cm, grandes cheminées',
                'wood_type' => 'fruitiers',
                'usage_type' => 'chauffage',
                'humidity_rate' => 16.8,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 155.00,
                'professional_price' => 140.00,
                'stock_quantity' => 4,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'category_id' => $chauffageCategory->id,
            ],
        ];
        $this->createProducts($fruitiersProducts);
        
        // SAPIN - 10 produits (résineux économique)
        $sapinProducts = [
            [
                'name' => 'Sapin Allumage - Sacs 25kg',
                'slug' => 'sapin-allumage-sacs-25kg',
                'description' => "Sapin sec pour allumage, en sacs de 25kg. Prend feu rapidement grâce à sa résine naturelle. Parfait pour démarrer vos feux. Prix très économique.",
                'short_description' => 'Sapin allumage rapide, très économique',
                'wood_type' => 'sapin',
                'usage_type' => 'chauffage',
                'humidity_rate' => 22.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 4.90,
                'stock_quantity' => 150,
                'min_order_quantity' => 5,
                'alert_stock_level' => 30,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Sapin 30cm - Palette Économique',
                'slug' => 'sapin-30cm-palette-economique',
                'description' => "Sapin en palette, format 30cm. Solution très économique pour chauffage d'appoint. Allumage facile, combustion rapide. Idéal en mélange avec des bois durs.",
                'short_description' => 'Sapin économique 30cm, allumage facile',
                'wood_type' => 'sapin',
                'usage_type' => 'chauffage',
                'humidity_rate' => 23.0,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 65.00,
                'stock_quantity' => 40,
                'min_order_quantity' => 1,
                'alert_stock_level' => 8,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Sapin 20cm - Sacs 40kg',
                'slug' => 'sapin-20cm-sacs-40kg',
                'description' => "Sapin format 20cm en sacs de 40kg. Bûchettes parfaites pour démarrage rapide. Résine naturelle pour allumage facile. Solution économique quotidienne.",
                'short_description' => 'Sapin 20cm bûchettes, démarrage rapide',
                'wood_type' => 'sapin',
                'usage_type' => 'chauffage',
                'humidity_rate' => 22.5,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 5.50,
                'stock_quantity' => 120,
                'min_order_quantity' => 4,
                'alert_stock_level' => 20,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Sapin Bûchettes 15cm - Super Allumage',
                'slug' => 'sapin-buchettes-15cm-super-allumage',
                'description' => "Très petites bûchettes sapin 15cm pour allumage ultra-rapide. Sacs de 20kg. Riches en résine. Indispensables pour démarrer facilement tous vos feux.",
                'short_description' => 'Sapin 15cm super allumage, ultra-rapide',
                'wood_type' => 'sapin',
                'usage_type' => 'chauffage',
                'humidity_rate' => 21.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 4.20,
                'stock_quantity' => 180,
                'min_order_quantity' => 6,
                'alert_stock_level' => 35,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Sapin 35cm - Stère Économique',
                'slug' => 'sapin-35cm-stere-economique',
                'description' => "Sapin en stère format 35cm. Solution très économique pour grand foyer. Combustion rapide mais efficace. Parfait pour chauffage d'appoint intense.",
                'short_description' => 'Sapin 35cm stère, solution très économique',
                'wood_type' => 'sapin',
                'usage_type' => 'chauffage',
                'humidity_rate' => 24.0,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 55.00,
                'stock_quantity' => 25,
                'min_order_quantity' => 1,
                'alert_stock_level' => 5,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Sapin Copeaux Allumage - Sacs 15kg',
                'slug' => 'sapin-copeaux-allumage-sacs-15kg',
                'description' => "Copeaux de sapin pour allumage instantané. Sacs de 15kg ultra-pratiques. S'enflamment immédiatement. Parfait complément pour allumage express.",
                'short_description' => 'Copeaux sapin, allumage instantané',
                'wood_type' => 'sapin',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 3.80,
                'stock_quantity' => 200,
                'min_order_quantity' => 8,
                'alert_stock_level' => 40,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Sapin Mix Tailles - Palette Starter',
                'slug' => 'sapin-mix-tailles-palette-starter',
                'description' => "Mélange sapin différentes tailles sur palette. Pack starter parfait pour débuter. Copeaux + bûchettes + bûches. Solution complète économique.",
                'short_description' => 'Sapin mix starter, solution complète',
                'wood_type' => 'sapin',
                'usage_type' => 'chauffage',
                'humidity_rate' => 22.8,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 75.00,
                'stock_quantity' => 35,
                'min_order_quantity' => 1,
                'alert_stock_level' => 7,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Sapin 25cm Standard - Sacs 30kg',
                'slug' => 'sapin-25cm-standard-sacs-30kg',
                'description' => "Sapin format standard 25cm en sacs de 30kg. Taille pratique pour petits poêles. Combustion vive. Prix mini pour chauffage économique quotidien.",
                'short_description' => 'Sapin 25cm standard, prix mini',
                'wood_type' => 'sapin',
                'usage_type' => 'chauffage',
                'humidity_rate' => 23.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 4.50,
                'stock_quantity' => 100,
                'min_order_quantity' => 5,
                'alert_stock_level' => 18,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Big Bag Sapin Économique - 1200kg',
                'slug' => 'big-bag-sapin-economique-1200kg',
                'description' => "Sapin en big bag 1200kg pour gros consommateurs. Solution ultra-économique. Livraison grue. Parfait pour chauffage d'appoint industriel.",
                'short_description' => 'Sapin big bag 1200kg, ultra-économique',
                'wood_type' => 'sapin',
                'usage_type' => 'chauffage',
                'humidity_rate' => 24.5,
                'conditioning' => 'big_bags',
                'unit_type' => 'sac',
                'price_per_unit' => 180.00,
                'professional_price' => 155.00,
                'stock_quantity' => 15,
                'min_order_quantity' => 1,
                'alert_stock_level' => 3,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Sapin Premium Sec 28cm',
                'slug' => 'sapin-premium-sec-28cm',
                'description' => "Sapin premium bien sec format 28cm. Qualité supérieure pour un résineux. Combustion plus régulière. Moins d'humidité. Stock limité qualité premium.",
                'short_description' => 'Sapin premium sec 28cm, qualité supérieure',
                'wood_type' => 'sapin',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.5,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 85.00,
                'stock_quantity' => 20,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $chauffageCategory->id,
            ],
        ];
        $this->createProducts($sapinProducts);

        // Continuer avec les autres essences...
        // (À cause de la limite de caractères, je vais créer un autre fichier pour les essences restantes)
    }
}