<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class UltimateWoodTypesSeeder extends Seeder
{
    private function createProducts($products)
    {
        foreach ($products as $productData) {
            $productData['status'] = 'active';
            $product = Product::create($productData);
            
            ProductImage::create([
                'product_id' => $product->id,
                'image_url' => '/storage/images/products/' . $product->slug . '-1.jpg',
                'alt_text' => $product->name . ' - Image principale',
                'sort_order' => 1,
                'is_primary' => true
            ]);
        }
    }

    public function run(): void
    {
        $chauffageCategory = Category::where('slug', 'bois-de-chauffage')->first();
        $cuissonCategory = Category::where('slug', 'bois-de-cuisson')->first();

        // ACACIA - 10 produits (bois très dense)
        $acaciaProducts = [
            [
                'name' => 'Acacia 25cm - Palette',
                'slug' => 'acacia-25cm-palette',
                'description' => "Acacia en palette, format 25cm. Bois très dense avec pouvoir calorifique élevé. Combustion lente et braises durables. Excellent pour chauffage de longue durée.",
                'short_description' => 'Acacia très dense, braises durables',
                'wood_type' => 'acacia',
                'usage_type' => 'chauffage',
                'humidity_rate' => 17.5,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 125.00,
                'professional_price' => 115.00,
                'stock_quantity' => 12,
                'min_order_quantity' => 1,
                'alert_stock_level' => 3,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Acacia 30cm - Stère Premium',
                'slug' => 'acacia-30cm-stere-premium',
                'description' => "Acacia premium en stère format 30cm. Bois extrêmement dense. Combustion très lente avec braises exceptionnellement durables. Top qualité pour experts.",
                'short_description' => 'Acacia premium, braises exceptionnelles',
                'wood_type' => 'acacia',
                'usage_type' => 'chauffage',
                'humidity_rate' => 16.8,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 135.00,
                'professional_price' => 125.00,
                'stock_quantity' => 8,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Acacia 20cm - Sacs 40kg',
                'slug' => 'acacia-20cm-sacs-40kg',
                'description' => "Acacia format 20cm en sacs de 40kg. Bûchettes très denses pour poêles haute performance. Combustion économique longue durée. Manipulation lourde mais efficace.",
                'short_description' => 'Acacia 20cm dense, longue durée',
                'wood_type' => 'acacia',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.0,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 11.50,
                'professional_price' => 10.80,
                'stock_quantity' => 40,
                'min_order_quantity' => 3,
                'alert_stock_level' => 8,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Acacia 35cm Chauffage Central',
                'slug' => 'acacia-35cm-chauffage-central',
                'description' => "Acacia format 35cm pour chaudières bois haute performance. Rendement énergétique maximum. Combustion très lente et régulière. Premium chauffage central.",
                'short_description' => 'Acacia 35cm rendement maximum',
                'wood_type' => 'acacia',
                'usage_type' => 'chauffage',
                'humidity_rate' => 17.2,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 145.00,
                'professional_price' => 135.00,
                'stock_quantity' => 10,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Acacia Bûchettes 15cm - Allumage Dense',
                'slug' => 'acacia-buchettes-15cm-allumage-dense',
                'description' => "Petites bûchettes acacia 15cm pour allumage avec bois dense. Sacs de 20kg. Plus dur à allumer mais brûle longtemps. Pour utilisateurs expérimentés.",
                'short_description' => 'Acacia 15cm allumage dense, experts',
                'wood_type' => 'acacia',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 8.20,
                'stock_quantity' => 50,
                'min_order_quantity' => 4,
                'alert_stock_level' => 10,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Big Bag Acacia Pro - 750kg',
                'slug' => 'big-bag-acacia-pro-750kg',
                'description' => "Acacia professionnel en big bag 750kg. Pour très gros consommateurs. Densité exceptionnelle. Livraison avec grue renforcée. Prix dégressifs pros.",
                'short_description' => 'Acacia pro 750kg, densité exceptionnelle',
                'wood_type' => 'acacia',
                'usage_type' => 'chauffage',
                'humidity_rate' => 16.5,
                'conditioning' => 'big_bags',
                'unit_type' => 'sac',
                'price_per_unit' => 365.00,
                'professional_price' => 335.00,
                'stock_quantity' => 4,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'is_professional_only' => true,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Acacia Premium XL 40cm',
                'slug' => 'acacia-premium-xl-40cm',
                'description' => "Acacia premium grande longueur 40cm. Pour très grandes cheminées haut de gamme. Combustion exceptionnellement longue. Produit rare exclusif.",
                'short_description' => 'Acacia premium XL 40cm, produit rare',
                'wood_type' => 'acacia',
                'usage_type' => 'chauffage',
                'humidity_rate' => 16.0,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 165.00,
                'professional_price' => 155.00,
                'stock_quantity' => 3,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Acacia Cuisson Lente - Sacs 25kg',
                'slug' => 'acacia-cuisson-lente-sacs-25kg',
                'description' => "Acacia spécial cuisson très lente. Sacs de 25kg. Maintient température constante très longtemps. Parfait pour cuissons longues et mijotage. Pro cuisine.",
                'short_description' => 'Acacia cuisson lente, température constante',
                'wood_type' => 'acacia',
                'usage_type' => 'cuisson',
                'humidity_rate' => 15.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 14.90,
                'stock_quantity' => 25,
                'min_order_quantity' => 2,
                'alert_stock_level' => 5,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Acacia Mix Économique - Palette',
                'slug' => 'acacia-mix-economique-palette',
                'description' => "Mélange acacia différentes qualités sur palette. Solution plus abordable pour profiter de la densité acacia. Combustion efficace prix réduit.",
                'short_description' => 'Acacia mix économique, densité abordable',
                'wood_type' => 'acacia',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.0,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 105.00,
                'professional_price' => 96.00,
                'stock_quantity' => 18,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Acacia Résistant - Sacs 30kg',
                'slug' => 'acacia-resistant-sacs-30kg',
                'description' => "Acacia naturellement résistant en sacs de 30kg. Bois imputrescible. Stockage extérieur possible. Combustion lente et économique. Très durable.",
                'short_description' => 'Acacia résistant, stockage extérieur',
                'wood_type' => 'acacia',
                'usage_type' => 'chauffage',
                'humidity_rate' => 17.8,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 9.90,
                'stock_quantity' => 35,
                'min_order_quantity' => 3,
                'alert_stock_level' => 8,
                'category_id' => $chauffageCategory->id,
            ],
        ];
        $this->createProducts($acaciaProducts);

        // CHÂTAIGNIER - 10 produits (bois de caractère)
        $chataignierProducts = [
            [
                'name' => 'Châtaignier 30cm - Sacs 40kg',
                'slug' => 'chataignier-30cm-sacs-40kg',
                'description' => "Châtaignier en sacs de 40kg, format 30cm. Bois de caractère avec tanins naturels. Combustion vive avec crépitements. Parfait pour ambiance chaleureuse.",
                'short_description' => 'Châtaignier de caractère, combustion vive',
                'wood_type' => 'chataignier',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.0,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 7.80,
                'stock_quantity' => 70,
                'min_order_quantity' => 4,
                'alert_stock_level' => 15,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Châtaignier 25cm - Palette Tradition',
                'slug' => 'chataignier-25cm-palette-tradition',
                'description' => "Châtaignier traditionnel en palette format 25cm. Bois régional de caractère. Combustion avec petits crépitements typiques. Ambiance authentique garantie.",
                'short_description' => 'Châtaignier tradition, ambiance authentique',
                'wood_type' => 'chataignier',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.5,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 95.00,
                'professional_price' => 88.00,
                'stock_quantity' => 20,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Châtaignier 33cm - Stère Régional',
                'slug' => 'chataignier-33cm-stere-regional',
                'description' => "Châtaignier régional en stère format 33cm. Circuit court local. Bois de pays avec caractère. Combustion typique avec sons authentiques de cheminée.",
                'short_description' => 'Châtaignier régional, circuit court',
                'wood_type' => 'chataignier',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.8,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 78.00,
                'professional_price' => 72.00,
                'stock_quantity' => 15,
                'min_order_quantity' => 1,
                'alert_stock_level' => 3,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Châtaignier 20cm - Sacs 25kg',
                'slug' => 'chataignier-20cm-sacs-25kg',
                'description' => "Châtaignier format 20cm en sacs de 25kg. Bûchettes de caractère pour petits foyers. Combustion vive et sonore. Manipulation facile. Ambiance chaleureuse.",
                'short_description' => 'Châtaignier 20cm caractère, ambiance chaleureuse',
                'wood_type' => 'chataignier',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 6.50,
                'stock_quantity' => 80,
                'min_order_quantity' => 5,
                'alert_stock_level' => 15,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Châtaignier Bûchettes 15cm - Allumage Sonore',
                'slug' => 'chataignier-buchettes-15cm-allumage-sonore',
                'description' => "Petites bûchettes châtaignier 15cm pour allumage sonore. Sacs de 20kg. Crépitements dès l'allumage. Ambiance feu de bois authentique immédiate.",
                'short_description' => 'Châtaignier 15cm crépitements, authentique',
                'wood_type' => 'chataignier',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 5.90,
                'stock_quantity' => 90,
                'min_order_quantity' => 6,
                'alert_stock_level' => 18,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Châtaignier 35cm Chauffage Central',
                'slug' => 'chataignier-35cm-chauffage-central',
                'description' => "Châtaignier format 35cm pour chauffage central. Résistant naturellement à l'humidité. Combustion régulière malgré les tanins. Bon pour systèmes étanches.",
                'short_description' => 'Châtaignier 35cm résistant, systèmes étanches',
                'wood_type' => 'chataignier',
                'usage_type' => 'chauffage',
                'humidity_rate' => 19.2,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 88.00,
                'professional_price' => 82.00,
                'stock_quantity' => 18,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Big Bag Châtaignier - 900kg',
                'slug' => 'big-bag-chataignier-900kg',
                'description' => "Châtaignier en big bag 900kg pour gros volumes. Bois de pays en grande quantité. Livraison avec grue. Prix avantageux pour gros consommateurs régionaux.",
                'short_description' => 'Châtaignier big bag 900kg, gros volumes',
                'wood_type' => 'chataignier',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.5,
                'conditioning' => 'big_bags',
                'unit_type' => 'sac',
                'price_per_unit' => 255.00,
                'professional_price' => 235.00,
                'stock_quantity' => 8,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Châtaignier Cuisson Rustique - Sacs 30kg',
                'slug' => 'chataignier-cuisson-rustique-sacs-30kg',
                'description' => "Châtaignier pour cuisson rustique. Sacs de 30kg. Apporte goût de terroir aux grillades. Combustion avec caractère. Parfait barbecues traditionnels.",
                'short_description' => 'Châtaignier cuisson rustique, goût terroir',
                'wood_type' => 'chataignier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 17.8,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 9.90,
                'stock_quantity' => 45,
                'min_order_quantity' => 3,
                'alert_stock_level' => 10,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Châtaignier Premium XL 40cm',
                'slug' => 'chataignier-premium-xl-40cm',
                'description' => "Châtaignier premium grande longueur 40cm. Pour grandes cheminées de caractère. Combustion longue avec crépitements. Produit régional premium rare.",
                'short_description' => 'Châtaignier premium XL 40cm, produit rare',
                'wood_type' => 'chataignier',
                'usage_type' => 'chauffage',
                'humidity_rate' => 18.0,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 98.00,
                'professional_price' => 90.00,
                'stock_quantity' => 6,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Châtaignier Résistant Extérieur - Palette',
                'slug' => 'chataignier-resistant-exterieur-palette',
                'description' => "Châtaignier naturellement résistant pour stockage extérieur. Palette spéciale. Imputrescible naturel. Pas de traitement chimique. Très pratique.",
                'short_description' => 'Châtaignier stockage extérieur, imputrescible',
                'wood_type' => 'chataignier',
                'usage_type' => 'chauffage',
                'humidity_rate' => 20.2,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 92.00,
                'professional_price' => 85.00,
                'stock_quantity' => 25,
                'min_order_quantity' => 1,
                'alert_stock_level' => 5,
                'category_id' => $chauffageCategory->id,
            ],
        ];
        $this->createProducts($chataignierProducts);

        // POMMIER - 10 produits (fruitier pur cuisson)
        $pommierProducts = [
            [
                'name' => 'Pommier Cuisson - Sacs 25kg',
                'slug' => 'pommier-cuisson-sacs-25kg',
                'description' => "Pommier pur pour cuisson, en sacs de 25kg. Arôme fruité délicat pour vos grillades. Combustion douce et régulière. Idéal pour viandes blanches et poissons.",
                'short_description' => 'Pommier pur, arôme fruité délicat',
                'wood_type' => 'pommier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 16.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 15.90,
                'stock_quantity' => 40,
                'min_order_quantity' => 2,
                'alert_stock_level' => 8,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Pommier BBQ Premium - Sacs 30kg',
                'slug' => 'pommier-bbq-premium-sacs-30kg',
                'description' => "Pommier premium spécial barbecue. Sacs de 30kg. Arôme fruité intense. Combustion lente parfaite pour grillades longues. Sans traitement, pur fruitier.",
                'short_description' => 'Pommier BBQ premium, arôme intense',
                'wood_type' => 'pommier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 15.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 17.90,
                'stock_quantity' => 35,
                'min_order_quantity' => 2,
                'alert_stock_level' => 7,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Pommier 28cm Four Pizza',
                'slug' => 'pommier-28cm-four-pizza',
                'description' => "Pommier format 28cm spécial four à pizza. Combustion douce et parfumée. Apporte saveur fruitée subtile aux pizzas. Format professionnel pizzerias.",
                'short_description' => 'Pommier 28cm pizza, saveur fruitée',
                'wood_type' => 'pommier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 15.8,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 125.00,
                'professional_price' => 108.00,
                'stock_quantity' => 8,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Pommier Fumage Doux - Sacs 20kg',
                'slug' => 'pommier-fumage-doux-sacs-20kg',
                'description' => "Pommier spécial fumage doux en sacs de 20kg. Arôme très délicat pour fumage à froid. Parfait pour saumons, truites et charcuteries fines.",
                'short_description' => 'Pommier fumage doux, très délicat',
                'wood_type' => 'pommier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 14.2,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 19.90,
                'stock_quantity' => 25,
                'min_order_quantity' => 2,
                'alert_stock_level' => 5,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Pommier Restaurant Pro - Palette',
                'slug' => 'pommier-restaurant-pro-palette',
                'description' => "Pommier professionnel sur palette pour restaurants. Calibrage précis. Arôme constant. Livraison prioritaire pour professionnels de la restauration.",
                'short_description' => 'Pommier pro restaurants, arôme constant',
                'wood_type' => 'pommier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 15.0,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 185.00,
                'professional_price' => 165.00,
                'stock_quantity' => 6,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'is_professional_only' => true,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Pommier Copeaux Fins - Sacs 15kg',
                'slug' => 'pommier-copeaux-fins-sacs-15kg',
                'description' => "Copeaux fins de pommier pour fumage précis. Sacs de 15kg. Combustion très contrôlée. Parfait pour fumoirs professionnels et amateurs exigeants.",
                'short_description' => 'Copeaux pommier fins, fumage précis',
                'wood_type' => 'pommier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 12.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 22.90,
                'stock_quantity' => 30,
                'min_order_quantity' => 2,
                'alert_stock_level' => 6,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Pommier Chauffage Parfumé - Sacs 40kg',
                'slug' => 'pommier-chauffage-parfume-sacs-40kg',
                'description' => "Pommier pour chauffage d'agrément parfumé. Sacs de 40kg. Embaume délicatement la maison. Combustion douce et chaleureuse. Ambiance fruitée.",
                'short_description' => 'Pommier chauffage parfumé, ambiance fruitée',
                'wood_type' => 'pommier',
                'usage_type' => 'chauffage',
                'humidity_rate' => 17.5,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 13.90,
                'stock_quantity' => 20,
                'min_order_quantity' => 3,
                'alert_stock_level' => 4,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Pommier Mix Verger - Palette',
                'slug' => 'pommier-mix-verger-palette',
                'description' => "Mélange pommier différentes variétés de verger. Palette artisanale. Arômes variés selon variétés. Circuit court producteur local. Authentique.",
                'short_description' => 'Pommier mix verger, circuit court',
                'wood_type' => 'pommier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 16.5,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 165.00,
                'professional_price' => 148.00,
                'stock_quantity' => 8,
                'min_order_quantity' => 1,
                'alert_stock_level' => 2,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Big Bag Pommier Pro - 500kg',
                'slug' => 'big-bag-pommier-pro-500kg',
                'description' => "Pommier professionnel en big bag 500kg. Pour restaurants gastronomiques et fumoirs industriels. Qualité constante. Livraison avec grue spécialisée.",
                'short_description' => 'Pommier pro 500kg, gastronomie',
                'wood_type' => 'pommier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 14.8,
                'conditioning' => 'big_bags',
                'unit_type' => 'sac',
                'price_per_unit' => 325.00,
                'professional_price' => 285.00,
                'stock_quantity' => 3,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'is_professional_only' => true,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Pommier Bûchettes 15cm Déco',
                'slug' => 'pommier-buchettes-15cm-deco',
                'description' => "Petites bûchettes pommier 15cm décoratives. Sacs de 20kg. Pour cheminées d'agrément parfumées. Combustion douce et aromatique. Décoratif et fonctionnel.",
                'short_description' => 'Pommier 15cm déco, cheminées parfumées',
                'wood_type' => 'pommier',
                'usage_type' => 'chauffage',
                'humidity_rate' => 17.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 11.90,
                'stock_quantity' => 35,
                'min_order_quantity' => 3,
                'alert_stock_level' => 7,
                'category_id' => $chauffageCategory->id,
            ],
        ];
        $this->createProducts($pommierProducts);

        // CERISIER - 10 produits (fruitier fumage premium)
        $cerisierProducts = [
            [
                'name' => 'Cerisier Fumage - Sacs 25kg',
                'slug' => 'cerisier-fumage-sacs-25kg',
                'description' => "Cerisier spécial fumage en sacs de 25kg. Arôme subtil et délicat pour fumage à froid et à chaud. Donne une couleur dorée aux aliments. Très apprécié des chefs.",
                'short_description' => 'Cerisier fumage, arôme subtil et délicat',
                'wood_type' => 'cerisier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 15.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 18.90,
                'stock_quantity' => 30,
                'min_order_quantity' => 1,
                'alert_stock_level' => 6,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Cerisier Premium Fumage - Sacs 20kg',
                'slug' => 'cerisier-premium-fumage-sacs-20kg',
                'description' => "Cerisier premium pour fumage haute gastronomie. Sacs de 20kg. Arôme d'exception. Couleur dorée parfaite. Utilisé par les meilleurs chefs cuisiniers.",
                'short_description' => 'Cerisier premium, haute gastronomie',
                'wood_type' => 'cerisier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 14.8,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 24.90,
                'stock_quantity' => 20,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Cerisier BBQ Gourmet - Sacs 30kg',
                'slug' => 'cerisier-bbq-gourmet-sacs-30kg',
                'description' => "Cerisier pour barbecue gourmet. Sacs de 30kg. Parfait pour viandes rouges premium. Arôme délicat qui sublime les saveurs. Sans traitement chimique.",
                'short_description' => 'Cerisier BBQ gourmet, sublime les saveurs',
                'wood_type' => 'cerisier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 15.2,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 21.90,
                'stock_quantity' => 25,
                'min_order_quantity' => 2,
                'alert_stock_level' => 5,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Cerisier Restaurant Pro - Stère 26cm',
                'slug' => 'cerisier-restaurant-pro-stere-26cm',
                'description' => "Cerisier professionnel format 26cm pour restaurants étoilés. Calibrage très précis. Arôme constant. Livraison prioritaire pour haute gastronomie.",
                'short_description' => 'Cerisier pro restaurants étoilés',
                'wood_type' => 'cerisier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 14.5,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 145.00,
                'professional_price' => 125.00,
                'stock_quantity' => 5,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'is_professional_only' => true,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Cerisier Copeaux Fins - Sacs 12kg',
                'slug' => 'cerisier-copeaux-fins-sacs-12kg',
                'description' => "Copeaux fins de cerisier pour fumage de précision. Sacs de 12kg. Combustion très contrôlée. Parfait pour fumoirs professionnels et concours BBQ.",
                'short_description' => 'Copeaux cerisier fins, fumage précision',
                'wood_type' => 'cerisier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 12.0,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 28.90,
                'stock_quantity' => 20,
                'min_order_quantity' => 1,
                'alert_stock_level' => 4,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Cerisier 28cm Four Pizza',
                'slug' => 'cerisier-28cm-four-pizza',
                'description' => "Cerisier format 28cm spécial four à pizza gourmet. Arôme délicat qui parfume subtilement les pizzas. Pour pizzerias haut de gamme recherchant l'excellence.",
                'short_description' => 'Cerisier 28cm pizza gourmet, excellence',
                'wood_type' => 'cerisier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 15.0,
                'conditioning' => 'steres',
                'unit_type' => 'stere',
                'price_per_unit' => 135.00,
                'professional_price' => 115.00,
                'stock_quantity' => 6,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Cerisier Chauffage Parfumé - Sacs 35kg',
                'slug' => 'cerisier-chauffage-parfume-sacs-35kg',
                'description' => "Cerisier pour chauffage d'agrément très parfumé. Sacs de 35kg. Embaume délicatement l'intérieur. Combustion douce et aromatique. Ambiance raffinée.",
                'short_description' => 'Cerisier chauffage parfumé, ambiance raffinée',
                'wood_type' => 'cerisier',
                'usage_type' => 'chauffage',
                'humidity_rate' => 16.8,
                'conditioning' => 'sacs_40kg',
                'unit_type' => 'sac',
                'price_per_unit' => 16.90,
                'stock_quantity' => 15,
                'min_order_quantity' => 2,
                'alert_stock_level' => 3,
                'category_id' => $chauffageCategory->id,
            ],
            [
                'name' => 'Big Bag Cerisier Pro - 400kg',
                'slug' => 'big-bag-cerisier-pro-400kg',
                'description' => "Cerisier professionnel en big bag 400kg. Pour fumoirs industriels et restaurants gastronomiques. Qualité premium constante. Livraison spécialisée avec grue.",
                'short_description' => 'Cerisier pro 400kg, fumoirs industriels',
                'wood_type' => 'cerisier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 14.2,
                'conditioning' => 'big_bags',
                'unit_type' => 'sac',
                'price_per_unit' => 385.00,
                'professional_price' => 345.00,
                'stock_quantity' => 2,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'is_professional_only' => true,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Cerisier Mix Verger - Palette Artisanale',
                'slug' => 'cerisier-mix-verger-palette-artisanale',
                'description' => "Mélange cerisier différentes variétés de vergers. Palette artisanale. Arômes variés selon types de cerises. Circuit court producteur spécialisé.",
                'short_description' => 'Cerisier mix verger, circuit court spécialisé',
                'wood_type' => 'cerisier',
                'usage_type' => 'cuisson',
                'humidity_rate' => 15.8,
                'conditioning' => 'palettes',
                'unit_type' => 'palette',
                'price_per_unit' => 195.00,
                'professional_price' => 175.00,
                'stock_quantity' => 4,
                'min_order_quantity' => 1,
                'alert_stock_level' => 1,
                'category_id' => $cuissonCategory->id,
            ],
            [
                'name' => 'Cerisier Bûchettes 15cm Déco Premium',
                'slug' => 'cerisier-buchettes-15cm-deco-premium',
                'description' => "Petites bûchettes cerisier 15cm décoratives premium. Sacs de 18kg. Pour cheminées d'agrément très parfumées. Combustion douce et aromatique d'exception.",
                'short_description' => 'Cerisier 15cm déco premium, exception',
                'wood_type' => 'cerisier',
                'usage_type' => 'chauffage',
                'humidity_rate' => 16.5,
                'conditioning' => 'sacs_25kg',
                'unit_type' => 'sac',
                'price_per_unit' => 14.90,
                'stock_quantity' => 25,
                'min_order_quantity' => 2,
                'alert_stock_level' => 5,
                'category_id' => $chauffageCategory->id,
            ],
        ];
        $this->createProducts($cerisierProducts);
    }
}